### GET
GET http://localhost:5050/api/traditions/test-destination-1

### GETS
GET http://localhost:5050/api/traditions?


### POST
POST http://localhost:5050/api/traditions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZHE2YzZiOTAwMDBpMHJyczJ5NWQxNzkiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUzODkzMDQxLCJleHAiOjE3NTM5Nzk0NDF9.TAcX9yTsm0niscfVGWDANyzReB3gXG0Yunqg3rJaXCE

{
    "title": "test destination 1",
    "cover": {
        "url": "https://google.com"
    },
    "content": "test tesssttt"
}

### PATCH
PATCH http://localhost:5050/api/traditions/cmdrbl07u0000ugsrps0mp4hx
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZHE2YzZiOTAwMDBpMHJyczJ5NWQxNzkiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUzOTYwODc5LCJleHAiOjE3NTQwNDcyNzl9.yzNmqLszfkKgsWO09TsjJWm44y4gxzoXfaI5kBtsjnI

{
    "cover": {
        "url": "https://www.google.com"
    }
}

### DELETE
DELETE http://localhost:5050/api/traditions/cmdrcvmr10002ugiedx6aqfca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZHE2YzZiOTAwMDBpMHJyczJ5NWQxNzkiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUzOTYwODc5LCJleHAiOjE3NTQwNDcyNzl9.yzNmqLszfkKgsWO09TsjJWm44y4gxzoXfaI5kBtsjnI

######## COMMENT

### POST
POST  http://localhost:5050/api/destinations/cmdmqfzf8000ci0ar6nc76h4k/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG1xZnoxejAwMDFpMGFyYTNydGJwODUiLCJ1c2VybmFtZSI6InVzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MzY5MTYyNywiZXhwIjoxNzUzNzc4MDI3fQ.pZ5Dly6kh7JFXWDq0RNiMvic6IjTTuFEe3Z0rd8BFXg

{
    "content": "test comment repply",
    "parentId": "cmdmursf10001i01rxm9xnzfl"
}

### DELETE
DELETE  http://localhost:5050/api/comments/cmdmut9oy0005i01rjrun0amd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG1xZnoxejAwMDFpMGFyYTNydGJwODUiLCJ1c2VybmFtZSI6InVzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MzY5MTYyNywiZXhwIjoxNzUzNzc4MDI3fQ.pZ5Dly6kh7JFXWDq0RNiMvic6IjTTuFEe3Z0rd8BFXg


######## BOOKMARK

### POST
POST  http://localhost:5050/api/destinations/cmdmqfzf8000ci0ar6nc76h4k/bookmark
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG1xZnoxejAwMDFpMGFyYTNydGJwODUiLCJ1c2VybmFtZSI6InVzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MzY5MTYyNywiZXhwIjoxNzUzNzc4MDI3fQ.pZ5Dly6kh7JFXWDq0RNiMvic6IjTTuFEe3Z0rd8BFXg

### DELETE
DELETE  http://localhost:5050/api/destinations/cmdmqfzf8000ci0ar6nc76h4k/bookmark
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG1xZnoxejAwMDFpMGFyYTNydGJwODUiLCJ1c2VybmFtZSI6InVzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MzY5MTYyNywiZXhwIjoxNzUzNzc4MDI3fQ.pZ5Dly6kh7JFXWDq0RNiMvic6IjTTuFEe3Z0rd8BFXg

######## LIKE 

### POST
POST  http://localhost:5050/api/destinations/cmdmqfzf8000ci0ar6nc76h4k/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG1xZnoxejAwMDFpMGFyYTNydGJwODUiLCJ1c2VybmFtZSI6InVzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MzY5MTYyNywiZXhwIjoxNzUzNzc4MDI3fQ.pZ5Dly6kh7JFXWDq0RNiMvic6IjTTuFEe3Z0rd8BFXg

### DELETE
DELETE  http://localhost:5050/api/destinations/cmdmqfzf8000ci0ar6nc76h4k/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG1xZnoxejAwMDFpMGFyYTNydGJwODUiLCJ1c2VybmFtZSI6InVzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MzY5MTYyNywiZXhwIjoxNzUzNzc4MDI3fQ.pZ5Dly6kh7JFXWDq0RNiMvic6IjTTuFEe3Z0rd8BFXg


########## GALLERY

### POST
POST  http://localhost:5050/api/destinations/cmdospert000cgup9ugvtb34g/gallery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG9qc3ptMTAwMDB1Z3MzYmVhZzV6a3oiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUzNzk0MzY4LCJleHAiOjE3NTM4ODA3Njh9.Qnnn4nB_P61xSCzs89RQd89C5rHavGbSpH-ue-BcvaQ

[
    {
        "url": "https://google.com2", "publicId": "saidisahdahd"
    }
]


### DELETE
DELETE  http://localhost:5050/api/destinations/cmdospert000cgup9ugvtb34g/gallery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZG9qc3ptMTAwMDB1Z3MzYmVhZzV6a3oiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUzNzk0MzY4LCJleHAiOjE3NTM4ODA3Njh9.Qnnn4nB_P61xSCzs89RQd89C5rHavGbSpH-ue-BcvaQ

[
    "cmdosufeg0007guvzgvcage5k",
    "cmdoswn3t0003gu6t31qbn5bj"
]