### REGISTER
POST http://localhost:5050/api/register
Content-Type: application/json

{
    "username": "gedeapriana",
    "password": "11111111"
}

### LOGIN
POST http://localhost:5050/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "11111111"
}

### LOGOUT
DELETE http://localhost:5050/api/logout

### ME
GET http://localhost:5050/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZHN3MXpxbjAwMDBpMGF5d3V2djM0M2MiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU0NzM2NjIzLCJleHAiOjE3NTQ3MzY2NTN9.ukkvKKxD8auuTqYos-7-x4cwLXPHUqPJoTb0T6aRRw4
Content-Type: application/json

### REFRESH TOKEN
GET http://localhost:5050/api/token